Bump spirv-header/tools/glslang (#5834)
* Back out "Update SPIRV submodules (#5815)"

This backs out commit e50aac13e2c161d672b137a62f6d66820d0f9ff1.

* Use upstream spirv-tools

* Fix bump-glslang.sh for newer versions of spirv-tools

* Use upstream glslang

* Add --do-fetch option to bump glslang

* Bump glslang and friends

Supersedes https://github.com/shader-slang/slang/pull/5815

* Regenerate glslang and spirv-tools outputs

* Fixes to slang-glslang

* Correct spirv intrinsic for OpImageSampleFootprintNV

Note that this currently fails validation with the following error:

```
error: line 145: Result <id> from OpSampledImage instruction must not appear as operand for OpImageSampleFootprintNV, since it is not specified as taking an OpTypeSampledImage. Found result <id> '55[%sampledImage]' as an operand of <id> '56[%resultVal]'.
  %sampledImage = OpSampledImage %54 %51 %40
```

This seems to be in error as the spec for
*SPV_NV_shader_image_footprint* states that "Sampled Image must be an
object whose type is OpTypeSampledImage"

https://refined-github-html-preview.kidonng.workers.dev/KhronosGroup/SPIRV-Registry/raw/refs/heads/main/extensions/NV/SPV_NV_shader_image_footprint.html

glslang also seems to fail with the same validation error

* Fix spv storage class test