Fix LLVM compile error on Windows
The following compile error is observed when build with LLVM on Windows:
```
D:/sbf/git/slang/test_wsl/source/slang-glslang/slang-glslang.cpp:39:31: error: static assertion expression is not an integral constant expression
   39 |     SLANG_COMPILE_TIME_ASSERT(SLANG_OFFSET_OF(TBuiltInResource, limits) > 0);
      |     ~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

To address the problem, SLANG_OFFSET_OF is defined as `offsetof` when
`__clang__` is defined.