Fix handling of include lines with spaces by slang-embed (#8909)
Since version 4.8.0, `unordered_dense` header is split into two files.
The main header includes `stl.h`, however, it uses preprocessor style
with spaces after the initial `#`[^1]. This is not handled by the
`slang-embed` which results in compilation error when building
executables:

```
gcc 14.3: /tmp/unknown-tofGRH.cpp(7723): error :  stl.h: No such file or directory
 7723 | #        include "stl.h"
      |                  ^~~~~~~
compilation terminated.
```

This PR makes the whitespace handling around the include directive a bit
more robust so that the `stl.h` file is embedded correctly.

Related to #6674

[^1]:
https://github.com/martinus/unordered_dense/blob/v4.8.0/include/ankerl/unordered_dense.h#L94

Signed-off-by: Marcin Serwin <marcin@serwin.dev>