Add missing file:line:message link error pattern
Linux GCC outputs link errors in format:
  /usr/include/stdio2.h:112: undefined reference to 'thing'

This is a 3-split pattern (file:line:message) that was not
handled. Added _parseFileLineMessage pattern to detect link
errors based on "undefined reference" in message content.

Fixes #9873